/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-10-16 20:57:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function checker(){\r\n");
      out.write("\tvar id = document.forms[\"inpForm\"][\"id\"];               \r\n");
      out.write("    var length = document.forms[\"inpForm\"][\"length\"];    \r\n");
      out.write("    var breadth = document.forms[\"inpForm\"][\"breadth\"];  \r\n");
      out.write("    var width =  document.forms[\"inpForm\"][\"width\"];  \r\n");
      out.write("    var price = document.forms[\"inpForm\"][\"price\"];  \r\n");
      out.write("    var icharge = document.forms[\"inpForm\"][\"icharge\"]; \r\n");
      out.write("    var ucharge =  document.forms[\"inpForm\"][\"ucharge\"];  \r\n");
      out.write("    var discount = document.forms[\"inpForm\"][\"discount\"];  \r\n");
      out.write("    var deposit = document.forms[\"inpForm\"][\"deposit\"]; \r\n");
      out.write("    var str_patt = new RegExp(\"[A-z]\");\r\n");
      out.write("    if (id.value == \"\" || length.value == \"\" || breadth.value == \"\" || width.value == \"\"\r\n");
      out.write("\t\t|| price.value == \"\" || icharge.value == \"\" \r\n");
      out.write("\t\t|| ucharge.value == \"\" || discount.value == \"\"|| deposit.value == \"\"){\r\n");
      out.write("\twindow.alert(\"Blank fields not accepted\"); \r\n");
      out.write("    return false;\r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    if (  str_patt.test(id.value)==true){\r\n");
      out.write("        window.alert(\"Check id type\"); \r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if ( str_patt.test(length.value)==true){\r\n");
      out.write("        window.alert(\"Check length type\"); \r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (  str_patt.test(breadth.value)==true){\r\n");
      out.write("        window.alert(\"Check breadth type\"); \r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (  str_patt.test(width.value)==true){\r\n");
      out.write("        window.alert(\"Check length type\"); \r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (  str_patt.test(price.value)==true){\r\n");
      out.write("        window.alert(\"Check price type\"); \r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (str_patt.test(icharge.value)==true){\r\n");
      out.write("        window.alert(\"Check icharge type\"); \r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (  str_patt.test(ucharge.value)==true){\r\n");
      out.write("        window.alert(\"Check iucharge type\"); \r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if ( str_patt.test(discount.value)==true){\r\n");
      out.write("        window.alert(\"Check discount type\"); \r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (  str_patt.test(deposit.value)==true){\r\n");
      out.write("        window.alert(\"Check deposit type\"); \r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<form action=\"DTHServlet\" method=\"get\" onSubmit=\"return checker()\" name=\"inpForm\">\r\n");
      out.write("<fieldset style=\"width:700px;height:800px\">\r\n");
      out.write("<table>\r\n");
      out.write("<h3>Register Setup box</h3>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Setup boxtype</td>\r\n");
      out.write("<td><select name=\"type\">\r\n");
      out.write("<option value=\"Standard\">Standard</option>\r\n");
      out.write("<option value=\"HD\">HD</option>\r\n");
      out.write("<option value=\"HD+\">HD+</option>\r\n");
      out.write("<option value=\"IPTV\">IPTV</option>\r\n");
      out.write("</select>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Setup box id\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type =\"text\" name=\"id\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td>\r\n");
      out.write("Setupbox features:</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"checkbox\" name=\"lang\" value=\"Multilingual channel\" />Multilingual channel<br>\r\n");
      out.write("<input type=\"checkbox\" name=\"lang\" value=\"guide\" />guide<br>\r\n");
      out.write("<input type=\"checkbox\" name=\"lang\" value=\"genre wise\"/ >genre wise<br>\r\n");
      out.write("<input type=\"checkbox\" name=\"lang\" value=\"channel guide\"/>channel guide<br>\r\n");
      out.write("<input type=\"checkbox\" name=\"lang\" value=\" live recording\"/>live recording<br>\r\n");
      out.write("<input type=\"checkbox\" name=\"lang\" value=\"recording\"/ >scheduled recording<br>\r\n");
      out.write("<input type=\"checkbox\" name=\"lang\" value=\"pause\"/>pause and play<br>\r\n");
      out.write("<input type=\"checkbox\" name=\"lang\" value=\" rewind\"/>rewind/forward</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Length\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type =\"text\" name=\"length\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Breadth\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type =\"text\" name=\"breadth\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Width\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type =\"text\" name=\"width\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Price\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type =\"text\" name=\"price\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Installation charges\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type =\"text\" name=\"icharge\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Upgradation charge\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type =\"text\" name=\"ucharge\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Discount\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type =\"text\" name=\"discount\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Billing Type</td>\r\n");
      out.write("<td><select name=\"btype\">\r\n");
      out.write("<option value=\"Post\">Post-Paid</option>\r\n");
      out.write("<option value=\"Pre\">Pre-Paid</option>\r\n");
      out.write("</select>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Refund deposit\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type =\"text\" name=\"deposit\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><br></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("Upload Inventory\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write(" <br>\r\n");
      out.write(" Select a file: <input type=\"file\" name=\"myFile\"><br><br>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td></td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type =\"submit\" name=\"submit\">\r\n");
      out.write("<input type=\"hidden\" name=\"register\" value=\"create\">\r\n");
      out.write("<input type =\"reset\" name=\"reset\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td></td>\r\n");
      out.write("<td>\r\n");
      out.write("<a href=\"readSetupbox.jsp\">Show set up box</a>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td></td>\r\n");
      out.write("<td>\r\n");
      out.write("<a href=\"updateSetupbox.jsp\">Update set up box</a>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td></td>\r\n");
      out.write("<td>\r\n");
      out.write("<a href=\"deleteSetupbox.jsp\">Delete set up box</a></td>\r\n");
      out.write("</table>\r\n");
      out.write("</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
